### ISSUE TITLE
Bad error message running stellar catalog lint

### ISSUE THREAD

**Issue by TripleDogDare** [polydawn/reach#1]
While running `stellar catalog lint`
```
WARN: module mirrors list failed to parse for "github.com/polydawn/stellar": Invalid byte while expecting start of value: 0x68
```
This happened due to not quoting mirror HTTPS link.
```
{
	"byModule": {
		"github.com/polydawn/stellar {
			"master": [github.com/polydawn/stellar.git]
		}
	}
}
```
Things that would be good to know json path + line/column numbers of failure. Actual character expected instead of ASCII hex code.

**Comment by warpfork** [comment]
Mostly a bug which needs improvements upstream in https://github.com/polydawn/refmt .
