### ISSUE TITLE
Mounting in the same location twice

### ISSUE THREAD

**Issue by TripleDogDare** [polydawn/reach#2]
Current module schema allows mounting to the same directory twice. This gives a very unhelpful error message.
Example:
```
beginning evaluation of step : install
-⟩ [12-15 21:54:58] -⟩ info: raw objects for ware "git:e4a778f4a0ddc0a8152367357318354a84c121e3" found cached, unpacking them to fileset --- wareID: git:e4a778f4a0ddc0a8152367357318354a84c121e3
exec invalid: readlink /var/lib/timeless/repeatr/executor/runc/cystd60s-qmvt7hhk-ddzabczd/chroot/bin: no such file or directory
-⟩ [12-15 21:54:59] -⟩ error: failed to evaluate formula --- error: exec invalid: readlink /var/lib/timeless/repeatr/executor/runc/cystd60s-qmvt7hhk-ddzabczd/chroot/bin: no such file or directory
stellar: evaluating module: failed evaluating operation "install": exec invalid: readlink /var/lib/timeless/repeatr/executor/runc/cystd60s-qmvt7hhk-ddzabczd/chroot/bin: no such file or directory
```
Solutions:
1. Fix error messages.
2. Swap mount location and ware references in the `input` mapping for modules.
    * Pros:
        1. More powerful: Allows mounting same ware to different locations.
        2. Sorting the imports makes obvious which ones are duplicates. Reducing incidence of my own stupid.
        3. Assignment is clearer, left value is assigned to be right value.
    * Cons:
        1. Breaks current heuristic of having ware references always on the left.

**Comment by warpfork** [comment]
+1 to solution 2.

Also a pro: the *formula* format is still paths-as-keys.  The module format is super, super incongruous for currently being shaped as it is.

**Comment by warpfork** [comment]
Solution 2 is implemented.  The situation leading to this bug is now inexpressible!  And thus, this is fixed.
